In [1]:
from cabinet_robot.joint_estimation import FG_twist_estimation, sturm_twist_estimation, EstimationResults
import jax
import numpy as np
from jaxlie import SE3 as jaxlie_SE3

%reload_ext autoreload
%autoreload 2

/home/tlips/.conda/envs/cabinet-manipulation/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


/home/tlips/Documents/cabinet-manipulation-eef/cat-ind-fg/articulation_estimation


In [2]:
# jax.config.update("jax_disable_jit", True)


In [3]:
original_part_pose = np.eye(4)
original_part_pose[2, 3] = 0.1

part_poses = [np.copy(original_part_pose)]
for _ in range(10):
    original_part_pose[0, 3] += 0.01
    original_part_pose[1, 3] += 0.005
    part_poses.append(np.copy(original_part_pose))


In [4]:
estimation = FG_twist_estimation(part_poses, stddev_pos=0.005, stddev_ori=0.02)
print(f"{estimation.twist=}")
print(f"{estimation.twist_frame_in_base_pose=}")

HUBER_DELTA = DeviceArray(1440.5648, dtype=float32)
type(joint_parameters_variable) = <class 'articulation_estimation.factor_graph.states.GeneralJointParametersVariable'>
Using VMAP to optimize all factor graph version
all_costs = DeviceArray([1.5821616e-03, 6.9037609e+00], dtype=float32)
best_costs = DeviceArray(0.00158216, dtype=float32)
joint_model_to_use = <JointFormulation.GeneralTwist: 1>
estimation.twist=DeviceArray([ 1.2669029e+00,  6.3334805e-01, -8.4499325e-06,
              7.6504663e-04, -2.9488269e-04,  1.6533064e-02],            dtype=float32)
estimation.twist_frame_in_base_pose=SE3(wxyz=[-9.9998999e-01  2.2999999e-04 -9.0000001e-05  4.9699997e-03], xyz=[-0.71287 -0.35164  0.10016])


In [5]:
# test: latent_pose second[0] = base_transform @ exp(twist * joint_state[0])

print(
    estimation.twist_frame_in_base_pose.as_matrix()
    @ jaxlie_SE3.exp(estimation.twist * estimation.current_joint_configuration).as_matrix()
)
print(
    estimation.twist_frame_in_base_pose.as_matrix()
    @ jaxlie_SE3.exp(estimation.twist * estimation.aux_data["joint_states"][0]).as_matrix()
)

import spatialmath.base as sm

# twist_in_poses_frame = sm.tr2adjoint(np.asarray(results.base_transform.as_matrix())) @ np.asarray(results.twist)
# print(jaxlie_SE3.exp(twist_in_poses_frame * results.aux_data["joint_states"][5]).as_matrix())


[[ 9.9999982e-01 -6.4510276e-04 -1.1500510e-05  9.9994063e-02]
 [ 6.4510136e-04  9.9999976e-01 -2.9847084e-05  5.0011009e-02]
 [ 1.1519791e-05  2.9839663e-05  1.0000000e+00  1.0000027e-01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[[ 9.9999982e-01  6.5992551e-04  1.1776356e-05 -8.5830688e-06]
 [-6.5992627e-04  9.9999970e-01  3.0541269e-05  1.8626451e-05]
 [-1.1756201e-05 -3.0549039e-05  1.0000000e+00  1.0000096e-01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [6]:
print(estimation.aux_data["joint_states"])

[[0.56120133]
 [0.5690947 ]
 [0.5769883 ]
 [0.58488166]
 [0.59277517]
 [0.60066855]
 [0.608562  ]
 [0.6164555 ]
 [0.6243489 ]
 [0.6322424 ]
 [0.6401358 ]]


## Explore methods for joint configuration estimation

In [7]:

#  part pose = = base_transform @ exp(twist * joint_state)
# so joint_state = log(base_transform^-1 @ part_pose) / twist
# but this last division can suffer from numerical issues...

part_pose = np.asarray(estimation.aux_data["latent_poses"]["second"][-1].as_matrix())
base_transform = np.asarray(estimation.twist_frame_in_base_pose.as_matrix())
twist = np.asarray(estimation.twist)

print(f"the GT joint configuration is {estimation.current_joint_configuration}")


the GT joint configuration is 0.6401358246803284


In [8]:
# naive joint configuration estimation -> numerical errors can dominate 
import spatialmath.base as sm

pose_in_twist_frame = sm.trinv(base_transform) @ part_pose
print(pose_in_twist_frame)
joint_state = sm.trlog(pose_in_twist_frame, twist=True,check=False) / twist
print(joint_state)
print(f"naive estimation = {np.mean(joint_state)}")

[[ 9.9994844e-01 -1.0153786e-02 -1.7876686e-04  8.0883688e-01]
 [ 1.0153701e-02  9.9994832e-01 -4.7073461e-04  4.0969858e-01]
 [ 1.8353737e-04  4.6889522e-04  9.9999988e-01  1.7051399e-04]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]
[ 0.64007269  0.64038825 -0.14997943  0.61411027  0.61432979  0.61415831]
naive estimation = 0.4955133144422448


In [9]:
# so weigh every factor according to the relative magnitude of the part twist to make a more robust estimate
pose_twist = sm.trlog(pose_in_twist_frame, twist=True,check=False)
normalized_pose_twist = pose_twist / np.linalg.norm(pose_twist,ord=1)
print(pose_twist/twist)
print(np.abs(normalized_pose_twist))
print(f"more robust estimation = {np.sum(pose_twist/twist * np.abs(normalized_pose_twist))}")

[ 0.64007269  0.64038825 -0.14997943  0.61411027  0.61432979  0.61415831]
[6.60724196e-01 3.30471011e-01 1.03260094e-06 3.82808736e-04
 1.47604103e-04 8.27334720e-03]
more robust estimation = 0.6399480214533965


In [10]:
# but even better method is required...
# do some explicit oultier detection or something?? 
# best option might be to use the results of the FG (which is however only valid in int the Twist frame of the FG..)

### Can we get rid of the 'twist frame' by expressing the twist in the base frame?

In [11]:
# Twist_expressed_in_base = sm.tr2adjoint(base_transform) @ twist
twist_expressed_in_base = sm.tr2adjoint(base_transform) @ twist
print(twist_expressed_in_base)
print(twist)

[ 1.26735039e+00  6.32588466e-01 -4.27035781e-05  7.65046551e-04
 -2.94882544e-04  1.65330638e-02]
[ 1.2669029e+00  6.3334805e-01 -8.4499325e-06  7.6504663e-04
 -2.9488269e-04  1.6533064e-02]


In [12]:
# now the twist is expressed in the base frame
# part_pose = part_pose[0] @ exp(twist * joint_state')


In [13]:
import rerun 
rerun.init("test-joint-estimation", spawn=True)


2023-02-27T10:17:08.329424Z  WARN rerun::run: Failed to bind address "0.0.0.0:9876". Another Rerun instance is probably running.


In [14]:
rerun.log_points(
    "part_poses",
    positions=np.array(part_poses)[:, :3, 3],
    colors=np.zeros((len(part_poses), 3), dtype=np.uint8),
    radii=0.01,
)

In [26]:
from cabinet_robot.visualisation import visualize_estimation
visualize_estimation(estimation)

(11, 4, 4)
